# Generated by Django 3.0.5 on 2020-04-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('sensor', models.TextField(verbose_name='sensor')),
                ('value', models.FloatField(verbose_name='value')),
                ('tree_id', models.TextField(verbose_name='tree_id')),
            ],
        ),
    ]
